### ISSUE TITLE
[Bug] Not compiling scripts

### ISSUE THREAD

**Issue by Kristinita** [ahkscript/SublimeAutoHotkey#37]
### Summary

Not compiling *.ahk* scripts.

### Expected behavior

Compiling *.ahk* to *.exe*, when I use `ahkcompile` command.

### Actual behavior

Not compile.

	command: ahkcompile
	Traceback (most recent call last):
	  File "E:\Sublime Text 3\sublime_plugin.py", line 553, in run_
	    return self.run()
	  File "ahkexec in E:\Sublime Text 3\Data\Installed Packages\AutoHotkey.sublime-package", line 44, in run
	TypeError: list indices must be integers, not str

### Steps to reproduce

I tested on Sublime Text without plugins. 

I open, for example, [this](https://gist.github.com/tmplinshi/6933557) script → save this script in *UTF-8 with BOM* →<kbd>Ctrl+Shift+P</kbd> → *AutoHotkey - Compile*.

### Environment

**Operating system and version:**
Windows 1067
**Sublime Text:**
Build 3114
**AutoHotkey**
Portable Unicode 32-bit

Thanks.

**Comment by Kristinita** [comment]
I'm sorry, I made a typo in path to _Ahk2Exe.exe_ file.
